services:
  db:
    image: postgres:16
    container_name: db_app
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis_app
    volumes:
      - redis_data:/data
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/dropit
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: sh -c "sleep 10 && alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

  nginx:
    image: nginx:1.27.1
    build: 
      dockerfile: "Dockerfile.nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

volumes:
  db_data:
  redis_data:
